name: Go application CI

on: [push, pull_request]

env:
  GOPATH: /home/runner/go

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set GOPATH
        run: |
          mkdir -p $GOPATH/src/github.com/guttosm/dummy-application
          mv $GITHUB_WORKSPACE/* $GOPATH/src/github.com/guttosm/dummy-application

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Build
        run: go build -v ./...

      - name: Unit tests
        run: go test -v ./...
